package org.broadinstitute.ddp.model.event;

public enum CopyAnswerTarget {
    PARTICIPANT_PROFILE_BIRTH_DATE,
    PARTICIPANT_PROFILE_FIRST_NAME,
    PARTICIPANT_PROFILE_LAST_NAME,
    OPERATOR_PROFILE_FIRST_NAME,
    OPERATOR_PROFILE_LAST_NAME
}
