tenant:
  "DB_NAME": "Username-Password-Authentication",

rules:
  - name: Force email verification
    script: ../force-email-verification.js
    enabled: true
    order: 1
  - name: Register User in Pepper
    script: ../register-user-in-pepper.js
    stage: login_success
    enabled: true
    order: 2

actions:
  - name: Force email verification
    code: ./actions/force-email-verification.js
    runtime: node18
    dependencies:
      - name: auth0
        version: 4.10.0
    deployed: true
    secrets:
      - name: M2M_DOMAIN
        value: '##AUTH0_DOMAIN##'
      - name: M2M_CLIENT_ID
        value: '##AUTH0_MGMT_CLIENT_ID##'
      - name: M2M_CLIENT_SECRET
        value: '##AUTH0_MGMT_CLIENT_SECRET##'
    status: built
    supported_triggers:
      - id: post-login
        version: v3

  - name: Register User in Pepper
    code: ../register-user-in-pepper-action.js
    runtime: node18
    dependencies:
      - name: request
        version: 2.88.2
      - name: google-cloud/logging
        version: 11.2.0
      - name: auth0
        version: 4.10.0
    deployed: true
    secrets:
      - name: pepperBaseUrl
        value: '##SERVER_BASE_URL##'
      - name: domain
        value: '##AUTH0_DOMAIN##'
      - name: M2M_CLIENT_ID
        value: '##AUTH0_MGMT_CLIENT_ID##'
      - name: M2M_CLIENT_SECRET
        value: '##AUTH0_MGMT_CLIENT_SECRET##'
    status: built
    supported_triggers:
      - id: post-login
        version: v3

triggers:
  post-login:
    - action_name: Force email verification
      display_name: Force email verification
      order: 1
    - action_name: Register User in Pepper
      display_name: Register User in Pepper
      order: 2

pages:
  - name: login
    html: ./pages/login.html
    enabled: true
  - name: password_reset
    html: ./pages/password_reset.html
    enabled: true

emailProvider:
  name: "sendgrid"
  enabled: true
  default_from_address: ##SENDGRID_EMAIL##
  credentials:
    api_key: ##SENDGRID_TOKEN##

emailTemplates:
  - template: reset_email
    body: ./emails/change_password.html
    from: Rare Genomes Project <##STUDY_EMAIL##>
    subject: >-
      {% if user.user_metadata.language == "es" %}
      Cambie su contraseña
      {% else %}
      Reset Your Password
      {% endif %}
    urlLifetimeInSeconds: 432000
    syntax: liquid
    enabled: true
  - template: verify_email
    body: ./emails/verify_email.html
    from: Rare Genomes Project <##STUDY_EMAIL##>
    resultUrl: '{{ application.callback_domain }}/email-verified-callback'
    subject: >-
      {% if user.user_metadata.language == "es" %}
      Confirme su cuenta en el Proyecto Genomas Raros
      {% else %}
      Confirm your Rare Genomes Project Account
      {% endif %}
    urlLifetimeInSeconds: 432000
    syntax: liquid
    enabled: true

# NOTE: client names must match what's in Auth0's dashboard, otherwise deploy
# will create new clients. Everytime deploy happens, client configurations here
# will overwrite what's in Auth0. If there are additional urls not in here then
# those need to be added back manually. Other settings not configured here will
# also need to be configured manually.
clients:
  - name: rgp-angular-client
    app_type: spa
    callbacks: [
      '##BASE_URL##/login-landing'
      ##LOCALHOST_CALLBACKS##
    ]
    allowed_logout_urls: [
      '##BASE_URL##',
      '##BASE_URL##/error',
      '##BASE_URL##/session-expired',
      '##BASE_URL##/email-verification-required'
      ##LOCALHOST_LOGOUTS##
    ]
    web_origins: [
      '##BASE_URL##'
      ##LOCALHOST_ORIGINS##
    ]
    client_metadata:
      study: RGP
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
    oidc_conformant: true
