# To make our config generation "compatible" with official dsdetoolbox, extract what is needed from it (this is not the base image)
FROM broadinstitute/dsde-toolbox:latest AS dsdetoolbox

FROM maven:3.6.0-jdk-11

# Copying necessary artifacts to enable configure.rb that lives in our own repo.
COPY --from=dsdetoolbox /usr/local/bin/consul-template /usr/local/bin/consul-template
COPY --from=dsdetoolbox /etc/consul-template/config/config.json /etc/consul-template/config/config.json
COPY --from=dsdetoolbox /usr/local/bin/vault /usr/local/bin/vault
ENV VAULT_ADDR https://clotho.broadinstitute.org:8200


RUN mkdir /app
WORKDIR /app
RUN ["echo","Installing gcloud tools..."]
RUN curl -o gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-197.0.0-linux-x86_64.tar.gz
RUN gunzip gcloud.tar.gz
RUN tar -xvf gcloud.tar
ENV PATH="/app/google-cloud-sdk/bin:${PATH}"
RUN gcloud components install beta --quiet
RUN gcloud components install pubsub-emulator --quiet
RUN gcloud components update --quiet

#install sheetappend utility. First install node
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

WORKDIR /tmp
#extracting sheetappend from ddp-angular repo. At some point we can get this from an npm repo
RUN svn export https://github.com/broadinstitute/ddp-angular/trunk/build-utils/sheetappend
RUN npm install -g sheetappend

RUN apt-get update && apt-get install -y \
    ruby \
    jq \
    default-mysql-client \
    netcat \
   && rm -rf /var/lib/apt/lists/*

ENV PUBSUB_EMULATOR_HOST "localhost:8442"

CMD "/bin/bash"
