service: pepper-api-spec
runtime: python37

# This setting will not matter except to prevent default automatic-scaling which prevents disabling
# earlier versions of this service
basic_scaling:
  max_instances: 1

handlers:
  - url: /spec/(.*\.(yaml|json))
    static_files: spec/\1
    upload: spec/(.*\.(yaml|json))
    secure: always

  - url: /(.*)
    static_files: index.html
    upload: index.html
    secure: always
