tenant:
  default_directory: Username-Password-Authentication

actions:
  - name: Force email verification
    code: ./actions/force-email-verification.js
    runtime: node18
    dependencies:
      - name: auth0
        version: 4.10.0
    deployed: true
    secrets:
      - name: M2M_DOMAIN
        value: '##AUTH0_DOMAIN##'
      - name: M2M_CLIENT_ID
        value: '##AUTH0_MGMT_CLIENT_ID##'
      - name: M2M_CLIENT_SECRET
        value: '##AUTH0_MGMT_CLIENT_SECRET##'
    status: built
    supported_triggers:
      - id: post-login
        version: v3

  - name: Google Sign In Restriction
    code: ./actions/google-signin-restriction.js
    deployed: false
    status: built
    supported_triggers:
      - id: post-login
        version: v3

  - name: Register User in Pepper
    code: ./actions/register-user-in-pepper-action.js
    dependencies:
      - name: request
        version: 2.88.2
    deployed: false
    secrets:
      - name: pepperBaseUrl
        value: '##SERVER_BASE_URL##'
      - name: domain
        value: '##AUTH0_DOMAIN##'
      - name: M2M_CLIENT_ID
        value: '##AUTH0_MGMT_CLIENT_ID##'
      - name: M2M_CLIENT_SECRET
        value: '##AUTH0_MGMT_CLIENT_SECRET##'
    status: built
    supported_triggers:
      - id: post-login
        version: v3

triggers:
  post-login:
    - action_name: Force email verification
      display_name: Force email verification
      order: 1
    - action_name: Google Sign In Restriction
      display_name: Google Sign In Restriction
      order: 2
    - action_name: Register User in Pepper
      display_name: Register User in Pepper
      order: 3

