tenant:
  default_directory: Username-Password-Authentication

actions:
  - name: Register User in Pepper
    code: ../register-user-in-pepper-action.js
    runtime: node18
    dependencies:
      - name: request
        version: 2.88.2
    deployed: true
    secrets:
      - name: pepperBaseUrl
        value: '##SERVER_BASE_URL##'
      - name: domain
        value: '##AUTH0_DOMAIN##'
      - name: M2M_CLIENT_ID
        value: '##AUTH0_MGMT_CLIENT_ID##'
      - name: M2M_CLIENT_SECRET
        value: '##AUTH0_MGMT_CLIENT_SECRET##'
    status: built
    supported_triggers:
      - id: post-login
        version: v3

triggers:
  post-login:
    - action_name: Register User in Pepper
      display_name: Register User in Pepper
      order: 1