tenant:
  default_directory: Username-Password-Authentication
  picture_url: '##BASE_URL##/assets/images/project-logo-dark.svg'

rules:
  - name: Register User in Pepper
    script: ../register-user-in-pepper.js
    stage: login_success
    enabled: true
    order: 1

actions:
  - name: Register User in Pepper v3
    code: ../register-user-in-pepper-action.js
    runtime: node18
    dependencies:
      - name: request
        version: 2.88.2
    deployed: false
    secrets:
      - name: pepperBaseUrl
        value: '##SERVER_BASE_URL##'
      - name: domain
        value: '##AUTH0_DOMAIN##'
      - name: M2M_CLIENT_ID
        value: '##AUTH0_MGMT_CLIENT_ID##'
      - name: M2M_CLIENT_SECRET
        value: '##AUTH0_MGMT_CLIENT_SECRET##'
    status: built
    supported_triggers:
      - id: post-login
        version: v3

triggers:
  post-login:
    - action_name: Register User in Pepper
      display_name: Register User in Pepper
      order: 1

pages:
  - name: login
    html: ./loginPage.html
    enabled: true
  - name: password_reset
    html: ./passwordResetPage.html
    enabled: true

emailProvider:
  name: "sendgrid"
  enabled: true
  default_from_address: ##SENDGRID_EMAIL##
  credentials:
    api_key: ##SENDGRID_TOKEN##

emailTemplates:
  - template: reset_email
    body: ./passwordResetEmail.html
    from: Prion <##STUDY_EMAIL##>
    resultUrl: '##SERVER_BASE_URL##/pepper/v1/post-password-reset?clientId={{ application.clientID }}'
    subject: >-
      {% if user.user_metadata.language == "es" %} Solicitud de cambio de contraseña
      {% elsif user.user_metadata.language == "he" %} בקשה להחלפת סיסמה
      {% elsif user.user_metadata.language == "zh" %} 密码变更请求
      {% else %} Password Change Request {% endif %}
    urlLifetimeInSeconds: 432000
    syntax: liquid
    enabled: true

# NOTE: client names must match what's in Auth0's dashboard, otherwise deploy
# will create new clients. Everytime deploy happens, client configurations here
# will overwrite what's in Auth0. If there are additional urls not in here then
# those need to be added back manually. Other settings not configured here will
# also need to be configured manually.
clients:
  - name: prion-angular-client
    app_type: spa
    callbacks: [
      '##BASE_URL##/login-landing'
      ##LOCALHOST_CALLBACKS##
    ]
    allowed_logout_urls: [
      '##BASE_URL##',
      '##BASE_URL##/error',
      '##BASE_URL##/session-expired'
      ##LOCALHOST_LOGOUTS##
    ]
    web_origins: [
      '##BASE_URL##'
      ##LOCALHOST_ORIGINS##
    ]
    client_metadata:
      study: PRION
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
    oidc_conformant: true
