package org.broadinstitute.ddp.model.activity.types;

public enum EventTriggerType {
    ACTIVITY_STATUS,
    DSM_NOTIFICATION,
    EXIT_REQUEST,
    GOVERNED_USER_REGISTERED,
    INVITATION_CREATED,
    JOIN_MAILING_LIST,
    MEDICAL_UPDATE,
    REACHED_AOM,
    REACHED_AOM_PREP,
    USER_NOT_IN_STUDY,
    USER_REGISTERED,
    WORKFLOW_STATE
}
