openapi: 3.0.3
servers:
  - url: https://pepper-dev.datadonationplatform.org/pepper/v1
    description: Development server (uses test data)
  - url: https://pepper.datadonationplatform.org/pepper/v1
    description: Production server (uses real data)
info:
  description: 'Pepper API specification'
  version: 'v1.27-370-ge7f3453f7'
  title: Pepper
  contact:
    email: info@datadonationplatform.org
  license:
    name: BSD 3-Clause (Revised)
    url: https://raw.githubusercontent.com/broadinstitute/ddp-study-server/develop/LICENSE
tags:
  - name: Admin
    description: administrative & internal calls
  - name: Activities
    description: >
      View and update survey responses. Activities will be translated to the preferred language
      if the study supports that language or will be provided in the fallback language. The preferred
      language can be specified in the "Accept-Language" header or, if missing, is taken from the user
      profile. The header contents always override the language from the profile.
  - name: Announcements
    description: >
      Messages from a study to participants. Will be translated to the preferred language
      if the study supports that language or will be provided in the fallback language. The preferred
      language can be specified in the "Accept-Language" header or, if missing, is taken from the user
      profile. The header contents always override the language from the profile.
  - name: Consent
    description: view and updates study consent elections
  - name: Invitations
    description: operations related to managing invitations
  - name: Mailing Address
    description: participant mailing address management
  - name: Medical Providers
    description: physicians, hospitals, and other medical providers
  - name: Operator & Participant
    description: participant & operator related calls
  - name: Studies
    description: view study-specific details
  - name: Study Admin
    description: study administration
  - name: Suggestion
    description: endpoints offering autosuggestion options
  - name: Temporary Users
    description: endpoints for temporary users
  - name: Workflow
    description: user's workflow in a study
  - name: Other
    description: other endpoints
paths:
  /healthcheck:
    $ref: 'endpoints/private/healthcheck.yml'
  /register:
    $ref: 'endpoints/private/register.yml'
  /auth0-log-event:
    $ref: 'endpoints/private/auth0-log-event.yml'
  /sendgrid-event:
    $ref: 'endpoints/private/sendgrid-event.yml'
  /temporary-users:
    $ref: 'endpoints/temporary-users.yml'
  /studies:
    $ref: 'endpoints/studies.yml'
  /mailing-list:
    $ref: 'endpoints/join.mailing.list.yml'
  /admin/studies/{study}/invitation-details:
    $ref: 'endpoints/admin.studies.invitation-details.yml'
  /admin/studies/{study}/invitation-lookup:
    $ref: 'endpoints/admin.studies.invitation-lookup.yml'
  /admin/studies/{study}/participants:
    $ref: 'endpoints/admin.studies.participants.yml'
  /admin/studies/{study}/participants/{user}:
    $ref: 'endpoints/admin.studies.participant.yml'
  /admin/studies/{study}/participants-lookup:
    $ref: 'endpoints/admin.studies.participants-lookup.yml'
  /admin/studies/{study}/user/{user}/login-account:
    $ref: 'endpoints/admin.studies.user.login-account.yml'
  /studies/{study}:
    $ref: 'endpoints/studies.study.yml'
  /studies/{study}/invitation-check:
    $ref: 'endpoints/studies.invitation-check.yml'
  /studies/{study}/invitation-verify:
    $ref: 'endpoints/studies.invitation-verify.yml'
  /studies/{study}/password-policy:
    $ref: 'endpoints/studies.password-policy.yml'
  /studies/{study}/suggestions/drugs:
    $ref: 'endpoints/studies.suggestions.drugs.yml'
  /studies/{study}/suggestions/cancers:
    $ref: 'endpoints/studies.suggestions.cancers.yml'
  /user/{user}/studies/{study}/activity-instance-select/{stableId}:
    $ref: 'endpoints/user.studies.activity-instance-select.yml'
  /user/{user}/studies/{study}/activities/{instance}/questions/{questionStableId}/options:
     $ref: 'endpoints/user.studies.activity.instance.question-options.yml'
  /studies/{study}/statistics:
    $ref: 'endpoints/studies.statistics.yml'
  /user/{user}:
    $ref: 'endpoints/user.yml'
  /user/{user}/profile:
    $ref: 'endpoints/user.profile.yml'
  /user/{user}/profile/address:
    $ref: 'endpoints/user.profile.addresses.yml'
  /user/{user}/profile/address/verify:
    $ref: 'endpoints/user.profile.addresses.verify.yml'
  /user/{user}/profile/address/{address}:
    $ref: 'endpoints/user.profile.address.yml'
  /user/{user}/profile/address/default:
    $ref: 'endpoints/user.profile.address.default.yml'
  /user/{user}/profile/address/temp/{instance}:
    $ref: 'endpoints/user.profile.address.temp.yml'
  /user/{user}/email:
    $ref: 'endpoints/user.email.yml'
  /user/{user}/password:
    $ref: 'endpoints/user.password.yml'
  /user/{user}/studies/{study}/activities:
    $ref: 'endpoints/user.studies.activities.yml'
  /user/{user}/studies/{study}/activities/{instance}:
    $ref: 'endpoints/user.studies.activity.yml'
  /user/{user}/studies/{study}/activities/{instance}/summary:
    $ref: 'endpoints/user.studies.activity.summary.yml'
  /user/{user}/studies/{study}/activities/{instance}/answers:
    $ref: 'endpoints/user.studies.activity.answers.yml'
  /user/{user}/studies/{study}/activities/{instance}/uploads:
    $ref: 'endpoints/user.studies.activity.uploads.yml'
  /user/{user}/studies/{study}/consents:
    $ref: 'endpoints/user.studies.consents.yml'
  /user/{user}/studies/{study}/consents/{instance}:
    $ref: 'endpoints/user.studies.consent.yml'
  /user/{user}/studies/{study}/invitations:
    $ref: 'endpoints/user.studies.invitations.yml'
  /user/{user}/studies/{study}/medical-providers/{institutionType}:
    $ref: 'endpoints/user.studies.medical-providers.yml'
  /user/{user}/studies/{study}/medical-providers/{institutionType}/{provider}:
    $ref: 'endpoints/user.studies.medical-provider.yml'
  /user/{user}/studies/{study}/participants:
    $ref: 'endpoints/user.studies.participants.yml'
  /user/{user}/studies/{study}/prequalifier:
    $ref: 'endpoints/user.studies.prequalifier.yml'
  /user/{user}/studies/{study}/announcements:
    $ref: 'endpoints/user.studies.announcements.yml'
  /user/{user}/studies/{study}/status:
    $ref: 'endpoints/user.studies.status.yml'
  /user/{user}/studies/{study}/workflow:
    $ref: 'endpoints/user.studies.workflow.yml'
  /user/{user}/studies/{study}/exit:
    $ref: 'endpoints/user.studies.exit.yml'
  /cancers:
    $ref: 'endpoints/cancers.yml'
  /autocomplete/institution:
    $ref: 'endpoints/autocomplete.institution.yml'
  /post-password-reset:
    $ref: 'endpoints/post-password-reset.yml'
components:
  parameters:
    $ref: 'components/parameters.yml'
  schemas:
    $ref: 'components/schemas.yml'
  responses:
    $ref: 'components/responses.yml'
  requestBodies:
    $ref: 'components/request-bodies.yml'
